services:
  TG-Antiharassment-Bot:
    container_name: TG-Antiharassment-Bot  # 容器名，可定义
    image: weijiaqaq/tg-antiharassment-bot:latest
    restart: unless-stopped
    env_file:
     - .env
    volumes:
     - ./data:/app/data
  cloudflare_web:
    container_name: cloudflare_web
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    command: ["python", "web/cloudflare_web.py"]
    depends_on:
      - TG-Antiharassment-Bot